production:
  # resources:
  #   useragent:
  #     wurflapi:
  #       wurfl_api_version: 1.1
  #       wurfl_lib_dir: APPLICATION_PATH/../library/Wurfl/1.1
  #       wurfl_config_file: APPLICATION_PATH/../library/Wurfl/1.1/resources/wurfl-config.php

staging:
  _extends: production

testing:
  _extends: production

development:
  _extends: production
